"""SQLite 数据库层（facade）。"""

from web.db_connection import DB_PATH, get_conn
from web.db_common import STATUSES, init_db, row_to_dict, enrich_task_row
from web.db_tasks import (
    active_task_video_ids,
    claim_pending_task,
    count_tasks,
    count_tasks_by_status,
    create_task,
    find_active_task_by_ip,
    find_by_platform_video,
    get_task,
    list_history,
    queue_ahead_count,
    requeue_interrupted_tasks,
    restart_media_extraction,
    retry_task,
    sync_monitor_video_engagement,
    update_task,
)
from web.db_settings import get_setting, get_settings_map, set_setting, set_settings
from web.db_monitors import (
    DEFAULT_SCAN_INTERVAL_SEC,
    count_monitor_videos,
    count_monitors,
    create_monitor,
    delete_monitor,
    find_monitor,
    get_monitor,
    get_monitor_video,
    list_due_monitors,
    list_monitor_videos,
    list_monitors,
    update_monitor,
    upsert_monitor_video,
)

__all__ = [
    "DB_PATH",
    "get_conn",
    "STATUSES",
    "DEFAULT_SCAN_INTERVAL_SEC",
    "init_db",
    "row_to_dict",
    "enrich_task_row",
    "find_by_platform_video",
    "get_task",
    "sync_monitor_video_engagement",
    "create_task",
    "find_active_task_by_ip",
    "active_task_video_ids",
    "update_task",
    "count_tasks",
    "count_tasks_by_status",
    "list_history",
    "requeue_interrupted_tasks",
    "retry_task",
    "restart_media_extraction",
    "claim_pending_task",
    "queue_ahead_count",
    "get_setting",
    "set_setting",
    "get_settings_map",
    "set_settings",
    "create_monitor",
    "get_monitor",
    "find_monitor",
    "list_monitors",
    "count_monitors",
    "update_monitor",
    "delete_monitor",
    "list_due_monitors",
    "get_monitor_video",
    "upsert_monitor_video",
    "list_monitor_videos",
    "count_monitor_videos",
]
